export const ACTIONS = Object.freeze({
  SHIFT_CREATED: 'SHIFT_CREATED',
  SHIFT_APPLIED: 'SHIFT_APPLIED',
  SHIFT_APPROVED: 'SHIFT_APPROVED',
  SHIFT_COMPLETED: 'SHIFT_COMPLETED',
  RATINGS_SUBMITTED: 'RATINGS_SUBMITTED',
});
