import { jsPDF } from "jspdf";

const safeValue = (value, fallback = "Not provided") => {
  if (value === null || value === undefined || value === "") {
    return fallback;
  }

  return String(value);
};

const addWrappedText = (doc, text, x, y, maxWidth, lineHeight = 6) => {
  const lines = doc.splitTextToSize(safeValue(text), maxWidth);
  doc.text(lines, x, y);

  return y + lines.length * lineHeight;
};

export const downloadIncidentPdf = (incident) => {
  if (!incident) {
    throw new Error("Incident information is unavailable.");
  }

  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;

    let y = 20;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("SecureShift", margin, y);

    y += 9;

    doc.setFontSize(16);
    doc.text("Incident Report", margin, y);

    y += 10;

    doc.setDrawColor(210, 218, 232);
    doc.line(margin, y, pageWidth - margin, y);

    y += 10;

    const addField = (label, value) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text(label, margin, y);

      y += 5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);

      y = addWrappedText(
        doc,
        safeValue(value),
        margin,
        y,
        contentWidth
      );

      y += 5;
    };

    addField("Incident ID", incident.id);
    addField("Reported By", incident.guard);
    addField("Shift / Location", incident.shift);
    addField("Date", incident.date);
    addField("Time", incident.time);
    addField("Status", incident.status);
    addField("Severity", incident.severity);

    // Description
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Incident Description", margin, y);

    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    y = addWrappedText(
      doc,
      incident.description,
      margin,
      y,
      contentWidth
    );

    y += 8;

    // Comments
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Employer Comments", margin, y);

    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    y = addWrappedText(
      doc,
      incident.comments,
      margin,
      y,
      contentWidth
    );

    y += 8;

    // Evidence
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Evidence", margin, y);

    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const photos = Array.isArray(incident.photos)
      ? incident.photos
      : [];

    doc.text(
      photos.length > 0
        ? `${photos.length} evidence photo${photos.length === 1 ? "" : "s"} attached to this incident.`
        : "No evidence photos attached.",
      margin,
      y
    );

    y += 10;

    // Footer
    doc.setDrawColor(225, 230, 240);
    doc.line(margin, y, pageWidth - margin, y);

    y += 7;

    doc.setFontSize(9);
    doc.setTextColor(110);
    doc.text(
      `Generated by SecureShift on ${new Date().toLocaleString()}`,
      margin,
      y
    );

    const safeId = safeValue(incident.id, "incident")
      .replace(/[^a-zA-Z0-9-_]/g, "-");

    doc.save(`SecureShift-${safeId}.pdf`);
  } catch (error) {
    console.error("Incident PDF generation failed:", error);
    throw new Error("Unable to generate the incident PDF.");
  }
};