name: Branch policy check (on PR)

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name and per-user limit
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const headRef = context.payload.pull_request.head.ref;        // branch name
            const prUser = context.payload.pull_request.user.login;       // PR author
            const pattern = new RegExp(`^${prUser}\\/(feature|fix|hotfix|release)\\/[-a-z0-9._]+$`);

            if (!pattern.test(headRef)) {
              core.setFailed(`Branch '${headRef}' must match: ${prUser}/(feature|fix|hotfix|release)/short-slug`);
              return;
            }

            const res = await github.rest.git.listMatchingRefs({
              owner, repo,
              ref: `heads/${prUser}/`
            });
            const count = res.data.length;
            core.info(`Active branches for ${prUser}: ${count}`);
            if (count > 2) {
              core.setFailed(`Per-user branch cap is 2. You currently have ${count}. Please delete or merge older branches.`);
            }
